/**
 * @file input.hpp
 * @brief Umbrella header for the Catalyst Input module. Pulls in the keyboard, mouse, gamepad, MIDI and USB HID headers
 * plus the input_state tracker, and declares the module-level functions.
 * @details Keyboard and mouse events are generated by the platform module's window backend and delivered through the sink
 * installed with platform::set_event_sink(). Gamepads have no window, so the input module drives them itself: install a
 * sink with input::set_event_sink() (usually the same one) and call poll_gamepads() once per frame.
 * License: CDDL-1.0 (see LICENSE).
 */

#pragma once

#include <catalyst/input/gamepad.hpp>
#include <catalyst/input/keyboard.hpp>
#include <catalyst/input/midi.hpp>
#include <catalyst/input/mouse.hpp>
#include <catalyst/input/state.hpp>
#include <catalyst/input/usb.hpp>

namespace catalyst::core
{
    class event_sink;
}

namespace catalyst::input
{

    /** @brief Name of the compiled-in backend ("win32" or "null"). */
    const char *module_name();

    /**
     * @fn set_event_sink
     * @brief Installs the sink that receives the events published by poll_gamepads(). Pass nullptr to stop publishing
     * (the snapshots returned by get_gamepad_state() keep updating). The sink and its dispatcher must outlive the
     * installation, and poll_gamepads() must be called on the dispatcher's owner thread.
     */
    void set_event_sink(core::event_sink *sink) noexcept;

    /** @brief The sink installed with set_event_sink(), or nullptr. */
    [[nodiscard]] core::event_sink *get_event_sink() noexcept;

} // namespace catalyst::input
