#!/usr/bin/env python3
"""Compile GLSL shaders to SPIR-V with glslc and embed them in a C++ header.

Usage:
    python scripts/embed_spirv.py --out <header.hpp> --namespace <ns> [--target-env vulkan1.3] \
        <name>=<shader.vert|.frag|.comp> [<name>=<shader> ...]

Each shader becomes `inline constexpr std::uint32_t <name>[] = {...};` inside `namespace <ns>`. The header is meant to
be checked in next to the sources so consumers do not need the Vulkan SDK at build time; re-run this script whenever a
shader changes. glslc is taken from PATH or from $VULKAN_SDK/Bin.

License: CDDL-1.0 (see LICENSE).
"""

from __future__ import annotations

import argparse
import os
import pathlib
import shutil
import struct
import subprocess
import sys
import tempfile


def find_glslc() -> str:
    exe = shutil.which("glslc")
    if exe:
        return exe
    sdk = os.environ.get("VULKAN_SDK")
    if sdk:
        for candidate in ("glslc.exe", "glslc"):
            path = pathlib.Path(sdk) / "Bin" / candidate
            if path.exists():
                return str(path)
    sys.exit("embed_spirv: glslc not found on PATH or in $VULKAN_SDK/Bin")


def compile_shader(glslc: str, source: pathlib.Path, target_env: str) -> bytes:
    with tempfile.TemporaryDirectory() as tmp:
        out = pathlib.Path(tmp) / (source.name + ".spv")
        cmd = [glslc, f"--target-env={target_env}", "-O", "-o", str(out), str(source)]
        subprocess.run(cmd, check=True)
        data = out.read_bytes()
    if len(data) % 4 != 0 or struct.unpack_from("<I", data, 0)[0] != 0x07230203:
        sys.exit(f"embed_spirv: {source} did not produce valid SPIR-V")
    return data


def format_words(data: bytes, indent: str = "    ", per_line: int = 8) -> str:
    words = struct.unpack("<%dI" % (len(data) // 4), data)
    lines = []
    for i in range(0, len(words), per_line):
        chunk = ", ".join(f"0x{w:08x}" for w in words[i : i + per_line])
        lines.append(f"{indent}{chunk},")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--out", required=True, type=pathlib.Path, help="header to write")
    parser.add_argument("--namespace", required=True, help="C++ namespace for the arrays")
    parser.add_argument("--target-env", default="vulkan1.3", help="glslc --target-env value")
    parser.add_argument("shaders", nargs="+", help="<array_name>=<glsl source path>")
    args = parser.parse_args()

    glslc = find_glslc()
    repo_root = pathlib.Path(__file__).resolve().parent.parent

    entries = []
    for spec in args.shaders:
        name, _, path = spec.partition("=")
        if not name or not path:
            sys.exit(f"embed_spirv: bad shader spec '{spec}', expected <name>=<path>")
        source = pathlib.Path(path).resolve()
        data = compile_shader(glslc, source, args.target_env)
        try:
            rel = source.relative_to(repo_root).as_posix()
        except ValueError:
            rel = source.name
        entries.append((name, rel, data))

    out = ["/**",
           " * SPDX-License-Identifier: CDDL-1.0",
           " * SPDX-FileCopyrightText: 2026-Current Catalyst",
           " *",
           " * @file",
           " * @brief SPIR-V bytecode embedded from GLSL sources. GENERATED by scripts/embed_spirv.py; do not edit by hand.",
           " * @details Regenerate with:",
           " *   python scripts/embed_spirv.py --out " + args.out.as_posix() + " --namespace " + args.namespace +
           " \\",
           " *       " + " ".join(f"{name}={rel}" for name, rel, _ in entries),
           " */",
           "",
           "#pragma once",
           "",
           "#include <cstddef>",
           "#include <cstdint>",
           "#include <span>",
           "",
           f"namespace {args.namespace}",
           "{",
           ""]

    for name, rel, data in entries:
        out.append(f"    /** SPIR-V for {rel} ({len(data)} bytes). */")
        out.append(f"    inline constexpr std::uint32_t {name}[] = {{")
        out.append(format_words(data, indent="        "))
        out.append("    };")
        out.append("")
        out.append(f"    inline std::span<const std::byte> {name}_bytes() noexcept")
        out.append("    {")
        out.append(f"        return std::as_bytes(std::span<const std::uint32_t>{{{name}}});")
        out.append("    }")
        out.append("")

    out.append(f"}} // namespace {args.namespace}")
    out.append("")

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(out), encoding="utf-8", newline="\n")
    print(f"embed_spirv: wrote {args.out} ({len(entries)} shaders)")


if __name__ == "__main__":
    main()
